[tasks.format]
args = ["fmt", "--", "--emit=files"]
command = "cargo"
install_crate = "rustfmt"

[tasks.clean]
args = ["clean"]
command = "cargo"

[tasks.build]
args = ["build", "--release"]
command = "cargo"
dependencies = ["clean"]

[tasks.test]
args = ["test"]
command = "cargo"
dependencies = ["clean"]

[tasks.release]
dependencies = ["format", "build"]
