[tasks.format]
args = ["fmt", "--", "--emit=files"]
command = "cargo"
install_crate = "rustfmt"

[tasks.clean]
args = ["clean"]
command = "cargo"

# [tasks.lint]
# install_crate = "clippy"
# command = "cargo"
# args = ["clippy"]

[tasks.build]
args = ["build"]
command = "cargo"
dependencies = ["clean"]

[tasks.test]
args = ["test"]
command = "cargo"
dependencies = ["clean"]

[tasks.release]
dependencies = [
  "format",
  "build",
  "test",
]
